# Generated by Django 6.0 on 2026-01-14 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("page_visited", models.CharField(default="/", max_length=500)),
                ("referrer", models.URLField(blank=True, default="", max_length=1000)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("visited_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Visitor Log",
                "verbose_name_plural": "Visitor Logs",
                "ordering": ["-visited_at"],
            },
        ),
    ]
