# Generated by Django 6.0 on 2025-12-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
