# Generated by Django 6.0 on 2025-12-29 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_initial"),
        ("users", "0002_visitor_address_visitor_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontent",
            name="administrator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_content",
                to="users.administrator",
            ),
        ),
        migrations.AlterField(
            model_name="sitecontent",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                db_index=True,
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
