# Generated by Django 6.0 on 2025-12-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_sitecontent_content_type_sitecontent_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecontent",
            name="deal_type",
            field=models.CharField(
                choices=[("RENT", "Rent"), ("BUY", "Buy"), ("INVEST", "Invest")],
                db_index=True,
                default="RENT",
                max_length=20,
            ),
        ),
    ]
