# Generated by Django 6.0 on 2026-01-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_sitecontent_deal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecontent",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="description_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="description_it",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="description_nl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="description_pt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="location_ar",
            field=models.CharField(
                blank=True,
                help_text="e.g. 3rd Floor, Building A",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="location_de",
            field=models.CharField(
                blank=True,
                help_text="e.g. 3rd Floor, Building A",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="location_en",
            field=models.CharField(
                blank=True,
                help_text="e.g. 3rd Floor, Building A",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="location_es",
            field=models.CharField(
                blank=True,
                help_text="e.g. 3rd Floor, Building A",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="location_fr",
            field=models.CharField(
                blank=True,
                help_text="e.g. 3rd Floor, Building A",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="location_it",
            field=models.CharField(
                blank=True,
                help_text="e.g. 3rd Floor, Building A",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="location_nl",
            field=models.CharField(
                blank=True,
                help_text="e.g. 3rd Floor, Building A",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="location_pt",
            field=models.CharField(
                blank=True,
                help_text="e.g. 3rd Floor, Building A",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="title_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="title_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="title_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="title_it",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="title_nl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="title_pt",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
