# Generated by Django 6.0 on 2026-01-14 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_sitecontent_description_ar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="content_images/")),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.sitecontent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
