# Generated by Django 6.0 on 2025-12-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("CONTACT", "Contact Request"),
                        ],
                        default="INFO",
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("TREATED", "Treated")],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
