# Generated by Django 6.0 on 2025-12-28 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactrequest",
            old_name="request_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="contactrequest",
            name="subject",
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="email",
            field=models.EmailField(default="admin@sunset-plaza.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("INVESTMENT", "Investment Inquiry"),
                    ("INFO", "General Information"),
                    ("MEETING", "Book a Meeting"),
                ],
                default="INFO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONTACTED", "Contacted"),
                    ("CLOSED", "Closed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="visitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_requests",
                to="users.visitor",
            ),
        ),
    ]
