# Generated by Django 6.0 on 2025-12-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_rename_request_date_contactrequest_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrequest",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
