# Generated by Django 6.0 on 2025-12-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chatbot", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotinteraction",
            name="visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="users.visitor",
            ),
        ),
        migrations.AddField(
            model_name="chatbotinteraction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chatbot.interestcategory",
            ),
        ),
    ]
